#!/usr/bin/env node
const program = require('commander')
const main = require('./src/main')

program
  .version('1.0.0')
  .description('Controlle homeassistant from the command line')
  .option('-a, --api-password [api-password]', 'API password')
  .option('-i, --ip [ip]', 'the ip or hostname of your homeassistant instance')
  .option('-p, --port [port]', 'the port of your homeassistant instance')
  .option('-v, --verbos', 'give more information during runtime')

program
  .command('call')
  .arguments('<domain> <service>')
  .description('Call homeassistant service')
  .option('-s, --service-data [data]', 'additional service data')
  .action(main('call', program))

program
  .command('state')
  .arguments('<entity>')
  .description('Query the state and subscribe to changes')
  .option('-s, --subscribe', 'subscribe to state changes')
  .action(main('state', program))

program.parse(process.argv)
